name: CI4

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Install Conan
        run: |
          pip3 install conan
          conan profile detect --force

      - name: Install Project Dependencies
        run: |
          conan install . --output-folder=build --build=missing -s build_type=Release

      - name: Configure and Build
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=build/build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release   
          cmake --build .
